### ISSUE TITLE
jekyll serve - configuration file issue

### ISSUE THREAD

**Issue by mslfire** [troymcginnis/Jekyll-Base-Foundation#1]
I get a LoadError when I try to serve. - I'm on Win 8 - require: cannot load such file -- jekyll-assets (loadError). 
<img width="347" alt="error" src="https://cloud.githubusercontent.com/assets/11971626/11907845/829bcb22-a594-11e5-8cc4-7425cc36519b.PNG">

**Comment by troymcginnis** [comment]
@mslfire Looks like you're missing some ruby requirements. I'm relatively unfamiliar with development on Windows machines, but could you paste your full error here?
